### ISSUE TITLE
Selam

### ISSUE THREAD

**Issue by ayazxxx** [melodyyxox/PHP_WORK1#1]
Bence bu depoda gelişmesi gereken bi çok şey var.Erken pes etmiş gibisin :)

**Comment by melodyyxox** [comment]
@ayazxxx Mahmut bey oradan buradan bana yazacağınıza neticeye gelin bence..

**Comment by melodyyxox** [comment]
@ayazxxx ordan oraya yelken çevirmek..Bilemedim..

**Comment by melodyyxox** [comment]
@ayazxxx  Ayrıca sosyal medya kullanmıyorum fazla.Reelciyim ben..Liseli aşıklar gibi yazışmayı da sevmem..konuşacaksanız telefondan konuşun..Yazacak kadar cesaretiniz var ise?!
